<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.registration.form.handler.fosub_bridge' shared service.

include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/Form/RegistrationFormHandlerInterface.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/Form/FOSUBRegistrationFormHandler.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/user-bundle/Util/TokenGeneratorInterface.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/user-bundle/Util/TokenGenerator.php';

$this->services['hwi_oauth.registration.form.handler.fosub_bridge'] = $instance = new \HWI\Bundle\OAuthBundle\Form\FOSUBRegistrationFormHandler(${($_ = isset($this->services['fos_user.user_manager']) ? $this->services['fos_user.user_manager'] : $this->load('getFosUser_UserManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_user.mailer']) ? $this->services['fos_user.mailer'] : $this->load('getFosUser_MailerService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_user.util.token_generator']) ? $this->services['fos_user.util.token_generator'] : ($this->services['fos_user.util.token_generator'] = new \FOS\UserBundle\Util\TokenGenerator())) && false ?: '_'}, 30);

$instance->setFormHandler(NULL);

return $instance;
