<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory_ck_editor.config_manager' shared service.

include_once $this->targetDirs[3].'/vendor/egeloen/ckeditor-bundle/Model/ConfigManagerInterface.php';
include_once $this->targetDirs[3].'/vendor/egeloen/ckeditor-bundle/Model/ConfigManager.php';

$this->services['ivory_ck_editor.config_manager'] = $instance = new \Ivory\CKEditorBundle\Model\ConfigManager();

$instance->setConfig('user_config', ['language' => 'en', 'width' => '100%', 'height' => '400px', 'filebrowserBrowseRoute' => 'media_index', 'filebrowserBrowseRouteAbsolute' => true, 'toolbar' => [0 => [0 => 'Undo', 1 => 'Redo'], 1 => [0 => 'Cut', 1 => 'Copy', 2 => 'Paste'], 2 => [0 => 'Bold', 1 => 'Italic', 2 => 'Underline', 3 => 'TextColor'], 3 => [0 => 'JustifyLeft', 1 => 'JustifyCenter', 2 => 'JustifyRight', 3 => 'JustifyBlock'], 4 => [0 => 'NumberedList', 1 => 'BulletedList', 2 => 'Checkbox'], 5 => [0 => 'BidiLtr', 1 => 'BidiRtl']], 'uiColor' => '#ffffff', 'removePlugins' => 'elementspath']);
$instance->setConfig('step_config', ['language' => 'en', 'width' => '100%', 'height' => '200px', 'filebrowserBrowseRoute' => 'media_index', 'filebrowserBrowseRouteAbsolute' => true, 'toolbar' => [0 => [0 => 'Undo', 1 => 'Redo'], 1 => [0 => 'Cut', 1 => 'Copy', 2 => 'Paste'], 2 => [0 => 'Bold', 1 => 'Italic', 2 => 'Underline', 3 => 'TextColor'], 3 => [0 => 'JustifyLeft', 1 => 'JustifyCenter', 2 => 'JustifyRight', 3 => 'JustifyBlock'], 4 => [0 => 'NumberedList', 1 => 'BulletedList', 2 => 'Checkbox'], 5 => [0 => 'BidiLtr', 1 => 'BidiRtl']], 'uiColor' => '#ffffff', 'removePlugins' => 'elementspath']);

return $instance;
