<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_imagine.binary.loader.default' shared service.

include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Binary/Loader/LoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Binary/Loader/FileSystemLoader.php';

return $this->services['liip_imagine.binary.loader.default'] = new \Liip\ImagineBundle\Binary\Loader\FileSystemLoader(${($_ = isset($this->services['liip_imagine.mime_type_guesser']) ? $this->services['liip_imagine.mime_type_guesser'] : $this->load('getLiipImagine_MimeTypeGuesserService.php')) && false ?: '_'}, ${($_ = isset($this->services['liip_imagine.extension_guesser']) ? $this->services['liip_imagine.extension_guesser'] : $this->load('getLiipImagine_ExtensionGuesserService.php')) && false ?: '_'}, ($this->targetDirs[3].'/app/../public_html/'));
