<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_imagine.binary.mime_type_guesser' shared service.

include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Binary/MimeTypeGuesserInterface.php';
include_once $this->targetDirs[3].'/vendor/liip/imagine-bundle/Binary/SimpleMimeTypeGuesser.php';

return $this->services['liip_imagine.binary.mime_type_guesser'] = new \Liip\ImagineBundle\Binary\SimpleMimeTypeGuesser(${($_ = isset($this->services['liip_imagine.mime_type_guesser']) ? $this->services['liip_imagine.mime_type_guesser'] : $this->load('getLiipImagine_MimeTypeGuesserService.php')) && false ?: '_'});
