<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIei7vwq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIei7vwq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIei7vwq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIei7vwq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIei7vwq\appProdProjectContainer([
    'container.build_hash' => 'Iei7vwq',
    'container.build_id' => 'c83cf99b',
    'container.build_time' => 1678987651,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIei7vwq');
