<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.resource_owner.facebook' shared service.

include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwnerInterface.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/FacebookResourceOwner.php';

return $this->services['hwi_oauth.resource_owner.facebook'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\FacebookResourceOwner(${($_ = isset($this->services['hwi_oauth.http_client']) ? $this->services['hwi_oauth.http_client'] : $this->load('getHwiOauth_HttpClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.http_utils']) ? $this->services['security.http_utils'] : $this->getSecurity_HttpUtilsService()) && false ?: '_'}, ['client_id' => '2704597856444479', 'client_secret' => 'b6c809f93ad07bdec6b21ba91e0bc92a', 'scope' => 'email', 'infos_url' => 'https://graph.facebook.com/me?fields=id,name,email,picture.type(large)', 'paths' => ['email' => 'email', 'profilepicture' => 'picture.data.url'], 'options' => []], 'facebook', ${($_ = isset($this->services['hwi_oauth.storage.session']) ? $this->services['hwi_oauth.storage.session'] : $this->load('getHwiOauth_Storage_SessionService.php')) && false ?: '_'});
