<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.http_client' shared service.

include_once $this->targetDirs[3].'/vendor/kriswallsmith/buzz/lib/Buzz/Client/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/buzz/lib/Buzz/Client/AbstractClient.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/buzz/lib/Buzz/Client/AbstractCurl.php';
include_once $this->targetDirs[3].'/vendor/kriswallsmith/buzz/lib/Buzz/Client/Curl.php';

$this->services['hwi_oauth.http_client'] = $instance = new \Buzz\Client\Curl();

$instance->setVerifyPeer(true);
$instance->setTimeout(5);
$instance->setMaxRedirects(5);
$instance->setIgnoreErrors(true);

return $instance;
