<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hwi_oauth.resource_owner.google' shared service.

include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwnerInterface.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/AbstractResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GenericOAuth2ResourceOwner.php';
include_once $this->targetDirs[3].'/vendor/hwi/oauth-bundle/OAuth/ResourceOwner/GoogleResourceOwner.php';

return $this->services['hwi_oauth.resource_owner.google'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\GoogleResourceOwner(${($_ = isset($this->services['hwi_oauth.http_client']) ? $this->services['hwi_oauth.http_client'] : $this->load('getHwiOauth_HttpClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.http_utils']) ? $this->services['security.http_utils'] : $this->getSecurity_HttpUtilsService()) && false ?: '_'}, ['client_id' => '690266354741-vg742hddgqcp5qumkmc3lvhv0dla6e07.apps.googleusercontent.com', 'client_secret' => 'm3a5C-q86wwReqOgbgd_NjJy', 'scope' => 'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile', 'paths' => [], 'options' => []], 'google', ${($_ = isset($this->services['hwi_oauth.storage.session']) ? $this->services['hwi_oauth.storage.session'] : $this->load('getHwiOauth_Storage_SessionService.php')) && false ?: '_'});
