<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'liip_imagine' shared service.

include_once $this->targetDirs[3].'/vendor/imagine/imagine/lib/Imagine/Image/ImagineInterface.php';
include_once $this->targetDirs[3].'/vendor/imagine/imagine/lib/Imagine/Image/AbstractImagine.php';
include_once $this->targetDirs[3].'/vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php';
include_once $this->targetDirs[3].'/vendor/imagine/imagine/lib/Imagine/Image/Metadata/MetadataReaderInterface.php';
include_once $this->targetDirs[3].'/vendor/imagine/imagine/lib/Imagine/Image/Metadata/AbstractMetadataReader.php';
include_once $this->targetDirs[3].'/vendor/imagine/imagine/lib/Imagine/Image/Metadata/ExifMetadataReader.php';

$this->services['liip_imagine'] = $instance = new \Imagine\Gd\Imagine();

$instance->setMetadataReader(new \Imagine\Image\Metadata\ExifMetadataReader());

return $instance;
