<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5nb7x1b\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5nb7x1b/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5nb7x1b.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5nb7x1b\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5nb7x1b\appDevDebugProjectContainer([
    'container.build_hash' => '5nb7x1b',
    'container.build_id' => '97763612',
    'container.build_time' => 1678992728,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5nb7x1b');
