<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Channel extends \AppBundle\Entity\Channel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'tags', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'rating', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'ratings', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'classification', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'countries', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'website', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'views', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'shares', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'media', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'featured', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'playas', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'comments', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'items', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sources', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sourceurl', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sourcetype', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'comment', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'label', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sublabel'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'description', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'tags', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'rating', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'ratings', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'classification', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'countries', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'website', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'views', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'shares', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'media', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'featured', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'playas', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'comments', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'items', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sources', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sourceurl', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sourcetype', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'comment', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'label', '' . "\0" . 'AppBundle\\Entity\\Channel' . "\0" . 'sublabel'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Channel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatured()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatured', []);

        return parent::getFeatured();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatured($featured)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatured', [$featured]);

        return parent::setFeatured($featured);
    }

    /**
     * {@inheritDoc}
     */
    public function setMedia(\MediaBundle\Entity\Media $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedia', [$media]);

        return parent::setMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedia', []);

        return parent::getMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function addCountry(\AppBundle\Entity\Country $countries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCountry', [$countries]);

        return parent::addCountry($countries);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCountry(\AppBundle\Entity\Country $countries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCountry', [$countries]);

        return parent::removeCountry($countries);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountries', []);

        return parent::getCountries();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountries($countries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountries', [$countries]);

        return parent::setCountries($countries);
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\AppBundle\Entity\Category $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', [$categories]);

        return parent::addCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\AppBundle\Entity\Category $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', [$categories]);

        return parent::removeCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories($categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', [$categories]);

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComment', []);

        return parent::getComment();
    }

    /**
     * {@inheritDoc}
     */
    public function setComment($comment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComment', [$comment]);

        return parent::setComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\AppBundle\Entity\Comment $comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', [$comments]);

        return parent::addComment($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\AppBundle\Entity\Comment $comments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', [$comments]);

        return parent::removeComment($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function getSources()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSources', []);

        return parent::getSources();
    }

    /**
     * {@inheritDoc}
     */
    public function setSources($sources)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSources', [$sources]);

        return parent::setSources($sources);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getViews()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViews', []);

        return parent::getViews();
    }

    /**
     * {@inheritDoc}
     */
    public function setViews($views)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViews', [$views]);

        return parent::setViews($views);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry($country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassification', []);

        return parent::getClassification();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassification($classification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassification', [$classification]);

        return parent::setClassification($classification);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRatings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRatings', []);

        return parent::getRatings();
    }

    /**
     * {@inheritDoc}
     */
    public function setRatings($ratings)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRatings', [$ratings]);

        return parent::setRatings($ratings);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', [$tags]);

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getSourcetype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSourcetype', []);

        return parent::getSourcetype();
    }

    /**
     * {@inheritDoc}
     */
    public function setSourcetype($sourcetype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSourcetype', [$sourcetype]);

        return parent::setSourcetype($sourcetype);
    }

    /**
     * {@inheritDoc}
     */
    public function getSourceurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSourceurl', []);

        return parent::getSourceurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSourceurl($sourceurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSourceurl', [$sourceurl]);

        return parent::setSourceurl($sourceurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getShares()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShares', []);

        return parent::getShares();
    }

    /**
     * {@inheritDoc}
     */
    public function getSharesnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSharesnumber', []);

        return parent::getSharesnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getViewsnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViewsnumber', []);

        return parent::getViewsnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setShares($shares)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShares', [$shares]);

        return parent::setShares($shares);
    }

    /**
     * {@inheritDoc}
     */
    public function number_format_short($n)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'number_format_short', [$n]);

        return parent::number_format_short($n);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlayas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlayas', []);

        return parent::getPlayas();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlayas($playas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlayas', [$playas]);

        return parent::setPlayas($playas);
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getSublabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSublabel', []);

        return parent::getSublabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSublabel($sublabel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSublabel', [$sublabel]);

        return parent::setSublabel($sublabel);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

}
